### PR TITLE
fix: socket io

### PR DESCRIPTION
**Pull request by MatthieuJnon**

### CODE REVIEW

**Comment by lako90** [comment]
This solution is working for me, thanks

**Comment by nenads** [comment]
What is status of this ?

**Comment by WeberJulian** [comment]
@dliuproduction would it be possible for you to approve this PR please ? This is a breaking bug.

**Comment by ptrkdy** [comment]
Hi, I think this would solve the following open discussion:

https://github.com/botfront/botfront/discussions/979

Also I think a version of the compiled JS needs to be added to CDN.

e.g.: https://cdn.jsdelivr.net/npm/rasa-webchat@1.0.0/
e.g.: https://storage.googleapis.com/cdn.botfront.cloud/botfront-widget-latest.js

Thanks!

**Review by cbissler — APPROVED** [review]
This solution is working for me too.
Would it be possible to merge this PR (and update the compiled build on CDN) ?
Currently, the 1.0.0 version of rasa-webchat can't work with de latest version of RASA and it's pretty annoying

**Comment by Gr8ayu** [comment]
Please add CDN of javascript for </script>

**Review by kenrilea — APPROVED** [review]

**Comment by WeberJulian** [comment]
Thank you @MatthieuJnon and @kenrilea  :)

**Review by coopeCoop — COMMENTED** [review]
Sockets fixed w/ proper version

**Pull request merged**
